services:
  - type: web
    name: typeracer-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false # Isi dengan IP server cPanel Anda / Domain cPanel
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: codr8681_Adhya
      - key: DB_PASSWORD
        sync: false # Isi dengan password DB Anda
      - key: DB_NAME
        value: codr8681_TypeRacer
      - key: JWT_SECRET
        generateValue: true
